#######################
### Gradle Settings ###
#######################
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx5G

##########################
### Framework Settings ###
##########################
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

mc_version=1.21.1
minecraft_version_range=[1.21.1,1.21.4]
neo_version=21.1.179
loader_version_range=[1,)

####################
### Mod Settings ###
####################
mod_id=novacore
mod_version=3.0.1
mod_name=NovaCore
mod_description=NovaCore is a library mod for all NovaMachina Mods
github_id=NovaCore
mod_group_id=novamachina.novacore
mod_authors=NovaMachina, Rempler
mod_license=CC BY-NC-SA 4.0

########################
### Release Settings ###
########################
curseforge_id=923669
modrinth_project_id=engHtMVe
release_type=release