#######################
### Gradle Settings ###
#######################
org.gradle.daemon=false
org.gradle.debug=false
org.gradle.jvmargs=-Xmx5G

##########################
### Framework Settings ###
##########################


####################
### Mod Settings ###
####################
mod_id=novacore
mod_version=4.0.0
mod_name=NovaCore
mod_description=NovaCore is a library mod for all NovaMachina Mods
github_id=NovaCore

########################
### Release Settings ###
########################
curseforge_id=923669
modrinth_project_id=engHtMVe
release_type=release